[build]
command = "npm run build"
base = "/"
publish = "build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# Not compatible with multiple routes audits
# see https://github.com/netlify/netlify-plugin-lighthouse/issues/278
#
# [plugins.inputs]
# fail_deploy_on_score_thresholds = "true"

[[plugins.inputs.audits]]
path = ""

# Set minimum thresholds for each report area
[plugins.inputs.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9

# to audit an HTML file other than index.html in the build directory
[[plugins.inputs.audits]]
path = "cv"

[plugins.inputs.audits.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9
