[build]
command = "npm run build"
base = "/"
publish = "build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# Set the plugin to run prior to deploy, failing the build if minimum thresholds aren't set
[plugins.inputs]
fail_deploy_on_score_thresholds = "true"

# Set minimum thresholds for each report area
[plugins.inputs.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9

