[build]
command = "npm run build"
base = "/"
publish = "build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# Set the plugin to run prior to deploy, failing the build if minimum thresholds aren't set
[plugins.inputs]
fail_deploy_on_score_thresholds = "true"

[[plugins.inputs.audits]]
path = "index.html"

# Set minimum thresholds for each report area
[plugins.inputs.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9

# to audit an HTML file other than index.html in the build directory
[[plugins.inputs.audits]]
path = "cv.html"

# you can specify thresholds per audit
[plugins.inputs.audits.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9
